[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false

[[redirects]]
from = "/home"
to = "/home"
status = 200
force = false

[[redirects]]
from = "/personal"
to = "/personal"
status = 200
force = false

[[redirects]]
from = "/garage"
to = "/garage"
status = 200
force = false

[[redirects]]
from = "/properties"
to = "/properties"
status = 200
force = false

[[redirects]]
from = "/market"
to = "/market"
status = 200
force = false

[[redirects]]
from = "/trader"
to = "/trader"
status = 200
force = false

[[redirects]]
from = "/changelogs"
to = "/changelogs"
status = 200
force = false

[[redirects]]
from = "/settings"
to = "/settings"
status = 200
force = false